const sharedGlobals = {
  clearInterval: "readonly",
  clearTimeout: "readonly",
  console: "readonly",
  globalThis: "readonly",
  queueMicrotask: "readonly",
  setInterval: "readonly",
  setTimeout: "readonly",
  URL: "readonly",
  URLSearchParams: "readonly",
};

const browserGlobals = {
  ...sharedGlobals,
  addEventListener: "readonly",
  cancelAnimationFrame: "readonly",
  ClipboardEvent: "readonly",
  CustomEvent: "readonly",
  document: "readonly",
  Element: "readonly",
  Event: "readonly",
  File: "readonly",
  getSelection: "readonly",
  HTMLElement: "readonly",
  KeyboardEvent: "readonly",
  localStorage: "readonly",
  navigator: "readonly",
  Node: "readonly",
  NodeFilter: "readonly",
  prompt: "readonly",
  requestAnimationFrame: "readonly",
  window: "readonly",
  __FEATHER_VERSION__: "readonly",
};

const nodeGlobals = {
  ...sharedGlobals,
  Buffer: "readonly",
  process: "readonly",
};

export default [
  {
    ignores: [
      ".tools/**",
      "_site/**",
      "coverage/**",
      "dist/**",
      "node_modules/**",
      "playwright-report/**",
      "test-results/**",
      "feathertext.js",
      "feathertext.min.js",
      "*.map",
    ],
  },
  {
    files: ["**/*.{js,mjs,cjs}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
    },
    linterOptions: {
      reportUnusedDisableDirectives: "warn",
    },
    rules: {
      "constructor-super": "error",
      "for-direction": "error",
      "getter-return": "error",
      "no-async-promise-executor": "error",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-cond-assign": ["error", "except-parens"],
      "no-const-assign": "error",
      "no-dupe-args": "error",
      "no-dupe-class-members": "error",
      "no-dupe-else-if": "error",
      "no-duplicate-case": "error",
      "no-ex-assign": "error",
      "no-fallthrough": "error",
      "no-func-assign": "error",
      "no-import-assign": "error",
      "no-invalid-regexp": "error",
      "no-irregular-whitespace": "error",
      "no-loss-of-precision": "error",
      "no-obj-calls": "error",
      "no-self-assign": "error",
      "no-setter-return": "error",
      "no-shadow-restricted-names": "error",
      "no-sparse-arrays": "error",
      "no-unexpected-multiline": "error",
      "no-unreachable": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-labels": "error",
      "no-unused-vars": [
        "warn",
        {
          args: "after-used",
          argsIgnorePattern: "^_",
          caughtErrors: "none",
          varsIgnorePattern: "^_",
        },
      ],
      "no-with": "error",
      "require-yield": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
    },
  },
  {
    files: ["src/**/*.js", "benchmark/**/*.mjs"],
    languageOptions: {
      globals: browserGlobals,
    },
  },
  {
    files: [
      "*.config.{js,mjs}",
      "build.mjs",
      "benchmark/**/*.mjs",
      "scripts/**/*.mjs",
      "test/**/*.mjs",
    ],
    languageOptions: {
      globals: nodeGlobals,
    },
  },
];
