name: release
on:
  push:
    tags:
      - 'v*.*.*'   # e.g., v0.1.0

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to create releases
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ensure tags available
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/feathertext.min.js
            dist/feathertext.esm.js
            dist/feathertext.cjs
            dist/feathertext.css
